
const generateFaqs = (city: string  ) => [
  { question: "Heavy monsoon performance in " + city, answer: "Modern solar panels generate electricity even on cloudy and rainy days, though at a reduced capacity. Our systems are specifically designed with durable mounting structures to withstand high winds and heavy rainfall typical of " + city + " monsoons." },
  { question: "Net metering availability", answer: "Yes, net metering is fully available in Karnataka. Excess power generated by your on-grid system is exported back to the MESCOM grid, and you are credited for it, effectively spinning your meter backward." },
  { question: "Potential savings", answer: "Most residential customers see a reduction of 80% to 90% in their monthly electricity bills. The exact savings depend on your roof space, energy consumption, and the size of the system installed." },
  { question: "Government subsidies", answer: "Residential installations are eligible for significant central financial assistance (subsidy) under the PM Surya Ghar Muft Bijli Yojana. We handle all the necessary documentation to ensure you receive your eligible subsidy directly to your bank account." },
  { question: "Commercial ROI", answer: "For commercial properties, the return on investment (ROI) is typically between 3 to 4 years due to higher commercial electricity tariffs and tax benefits like accelerated depreciation." }
];

const generateCityData = (cityName:string) => ({
  title: `Solar Suppliers In ${cityName} | Mahati Enterprises`,
  description: `Join the renewable revolution with Mahati Enterprises in ${cityName}. We deliver high-efficiency solar solutions tailored for ${cityName}'s unique climate.`,
  city: cityName,
  heroSubtitle: "YOUR LOCAL SOLAR EXPERTS",
  heroTitle: "Power Your Home & Business with Clean Solar Energy in",
  heroTitleHighlight: cityName,
  heroDesc: [`Join the renewable revolution with Mahati Enterprises. We deliver high-efficiency solar solutions tailored for ${cityName}'s unique climate, ensuring maximum savings and reliability.`],
  benefitsTitle: `Why Choose Mahati Enterprises for Solar in ${cityName}?`,
  benefitsSubtitle: "We provide comprehensive solar solutions designed to maximize your ROI while minimizing environmental impact.",
  benefits: [
    { title: "Bill Reduction", desc: "Drastically lower or eliminate your monthly electricity bills from day one.", icon: "payments" },
    { title: "Reliable Power", desc: `Ensure uninterrupted power supply even during ${cityName}'s heavy monsoon power cuts.`, icon: "battery_charging_full" },
    { title: "Government Subsidies", desc: "We assist in navigating and claiming maximum available state and central subsidies.", icon: "account_balance" },
    { title: "Eco-Friendly", desc: "Reduce your carbon footprint and contribute to a greener, sustainable future.", icon: "eco" }
  ],
  faqs: generateFaqs(cityName)
});

export const mangaloreData = generateCityData("Mangalore");
export const udupiData = generateCityData("Udupi");
export const manipalData = generateCityData("Manipal");
export const moodabidriData = generateCityData("Moodabidri");
export const mulkiData = generateCityData("Mulki");
